const sound = {
    brushColorChange: new Audio('./sound/brushColorChange.wav'),
    brushPaint: new Audio('./sound/brushPaint.wav'),
    brushSplat: new Audio('./sound/brushSplat.wav'),
    dogBark: new Audio('./sound/dogBark.ogg'),
    dogEat: new Audio('./sound/dogEat.ogg'),
    dogLick: new Audio('./sound/dogLick.ogg'),
    dogPoop: new Audio('./sound/dogPoop.ogg'),
    dogShock: new Audio('./sound/dogShock.ogg'),
    error: new Audio('./sound/error.wav'),
    foliagePlant: new Audio('./sound/foliagePlant.wav'),
    select: new Audio('./sound/select.wav'),
    grabPick: new Audio('./sound/grabPick.wav'),
    personHappy: new Audio('./sound/personHappy.ogg'),
    personRandomize: new Audio('./sound/personRandomize.wav'),
    personShock: new Audio('./sound/personShock.ogg'),
    save: new Audio('./sound/save.ogg'),
    timeAccel: new Audio('./sound/timeAccel.wav'),
    timeFreeze: new Audio('./sound/timeFreeze.wav'),
    timeUnfreeze: new Audio('./sound/timeUnfreeze.wav'),
    toolUnlock: new Audio('./sound/toolUnlock.wav'),
};